//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FinalYearProject.Models
{
    using System;

    public partial class Comment
    {
        public int Comment_Id { get; set; }
        public int Pat_Id { get; set; }
        public int Doc_Id { get; set; }
        public string Text { get; set; }
        public Nullable<double> Rating { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public Nullable<bool> Commenter { get; set; }
    
        public virtual Doctor Doctor { get; set; }
        public virtual Patient Patient { get; set; }
    }
}
