//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FinalYearProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Notification
    {
        public int Notification_Id { get; set; }
        public Nullable<int> Pat_Id { get; set; }
        public int Doc_Id { get; set; }
        public string Name { get; set; }
        public string Message { get; set; }
        public System.DateTime StartTime { get; set; }
        public bool Status { get; set; }
    
        public virtual Doctor Doctor { get; set; }
        public virtual Patient Patient { get; set; }
    }
}
