//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FinalYearProject.Models
{

    public partial class PatientDoctors
    {
        public int Pat_Id { get; set; }
        public int Doc_Id { get; set; }
        public bool Pat_Confidential { get; set; }
        public int Recovery_Status { get; set; }
    }
}
