//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FinalYearProject.Models
{
    using System;

    public partial class Prescription
    {
        public int Prescription_Id { get; set; }
        public int Pat_Id { get; set; }
        public int Doc_Id { get; set; }
        public string Medicine_Name { get; set; }
        public string Type { get; set; }
        public Nullable<int> Amount { get; set; }
        public Nullable<int> Frequency { get; set; }
        public string Purpose { get; set; }
    
        public virtual Doctor Doctor { get; set; }
        public virtual Patient Patient { get; set; }
    }
}
